apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: vaishali293/vaishali2993:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:smart@vt2@postgres-service:5432/PROJECT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: PROJECT
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: smart@vt2
