
version: '3.8'

services:
  web:
    build: .  
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_NAME: PROJECT
      DB_USER: postgres
      DB_PASSWORD: smart@vt2
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: PROJECT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smart@vt2
    ports:
      - "5432:5432"














