
version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sql server
    networks:
      - app-network

  sql server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    restart: always
    environment:
      MSSQL_USER: vaishali
      MSSQL_PASSWORD: librarymgmt2393
      MSSQL_DATABASE: "PROJECT"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network













