CREATE DATABASE PROJECT

Use PROJECT
go
Create Schema Record

go



Create Table Record.Book(
BookID INT NOT NULL IDENTITY PRIMARY KEY,
Title VARCHAR(255) NOT NULL,
ISBN VARCHAR(20) NOT NULL,

Genre VARCHAR(50),
PublishedDate DATE NOT NULL,
QuantityInStock INT NOT NULL,

)

CREATE TABLE  Record.Member(
 MemberID INT NOT NULL IDENTITY  PRIMARY KEY,
 MemberName VARCHAR(255) NOT NULL,
 ContactNumber VARCHAR(15) NOT NULL,
 Email VARCHAR(255) NOT NULL,
 Address Varchar(255) NOT NULL
 )
 
CREATE TABLE Record.Issues(
 ISSUEID INT NOT NULL IDENTITY PRIMARY KEY,
 Title VARCHAR(1000) NOT NULL,
 MemberName VARCHAR(1000) NOT NULL,
 IssueDate DATE NOT NULL,
 ReturnDate DATE NOT NULL,

 )
 CREATE TABLE Record.Staff(
 StaffID INT NOT NULL IDENTITY PRIMARY KEY,
 Staffname VARCHAR(255) NOT NULL,
 Password VARCHAR(1000) NOT NULL
 )