CREATE DATABASE PROJECT

Use PROJECT
go



Create Table Book(
BookID SERIAL  PRIMARY KEY,
Title VARCHAR(255) NOT NULL,
ISBN VARCHAR(20) NOT NULL,

Genre VARCHAR(50),
PublishedDate DATE NOT NULL,
QuantityInStock INT NOT NULL,

);

CREATE TABLE  Member(
 MemberID SERIAL PRIMARY KEY,
 MemberName VARCHAR(255) NOT NULL,
 ContactNumber VARCHAR(15) NOT NULL,
 Email VARCHAR(255) NOT NULL,
 Address Varchar(255) NOT NULL
 );
 
CREATE TABLE Issues(
 ISSUEID SERIAL PRIMARY KEY,
 Title VARCHAR(1000) NOT NULL,
 MemberName VARCHAR(1000) NOT NULL,
 IssueDate DATE NOT NULL,
 ReturnDate DATE NOT NULL,

 );
 CREATE TABLE Staff(
 StaffID SERIAL PRIMARY KEY,
 Staffname VARCHAR(255) NOT NULL,
 Password VARCHAR(1000) NOT NULL
 );
